apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec:
      containers:
        - name: python-container
          image: ${{ secrets.DOCKER_USERNAME }}/test-python:latest
          ports:
            - containerPort: 8000
        - name: javascript-container
          image: ${{ secrets.DOCKER_USERNAME }}/test-javascript:latest
          ports:
            - containerPort: 8001
        - name: java-container
          image: ${{ secrets.DOCKER_USERNAME }}/test-java:latest
          ports:
            - containerPort: 8002
