apiVersion: v1
kind: Service
metadata:
  name: multi-container-service
spec:
  selector:
    app: multi-container-app
  ports:
    - name: python-port
      protocol: TCP
      port: 80
      targetPort: 8000
    - name: javascript-port
      protocol: TCP
      port: 81
      targetPort: 8001
    - name: java-port
      protocol: TCP
      port: 82
      targetPort: 8002