name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Build Docker Images
        run: |
          docker build -t myregistry/test-python:latest -f docker/Dockerfile.python .
          docker build -t myregistry/test-javascript:latest -f docker/Dockerfile.javascript .
          docker build -t myregistry/test-java:latest -f docker/Dockerfile.java .
          docker push myregistry/test-python:latest
          docker push myregistry/test-javascript:latest
          docker push myregistry/test-java:latest
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
      - name: Run Tests
        run: |
          docker run myregistry/test-python:latest
          docker run myregistry/test-javascript:latest
          docker run myregistry/test-java:latest
